import type { ContractGroup, Contracts } from "./types";

const MAINNET: ContractGroup = {
  MINTER: "KT1UcPwP7Usus8pFFXVQPcW5VZpkhf3LZZ1X",
  OVEN_PROXY: "KT1JdufSdfg3WyxWJcCRNsBFV9V3x9TQBkJ2",
  OVEN_FACTORY: "KT1Mgy95DVzqVBNYhsW93cyHuB57Q94UFhrh",
  TOKEN: "KT1K9gCRgaLRFKTErYt1wVxA3Frb9FjasjTV",
  OVEN_REGISTRY: "KT1Ldn1XWQmk7J4pYgGFjjwV57Ew8NYvcNtJ",
  DEVELOPER_FUND: "KT1SorR4UFBkUJeYVbtXZBNivUV1cQM6AqRR",
  STABILITY_FUND: "KT1AvxXZ3dgnvmUuuv7vCNeDRmxcZaArhPBy",
  ORACLE: "KT1E5wabXnFjbCTWJH7siBxVuxNUmyXWD5Gz",
  YOUVES_PROXY: "KT1ExbCyFbsvPQTUitHAK7HSfYkJgiCtBGpM",
  HARBINGER_NORMALIZER: "KT1AdbYiPYb5hDuEuVrfxmFehtnBCXv4Np7r",
  LIQUIDITY_POOL: "KT1AxaBxkFLCUi3f8rdDAAxBKHfzY8LfKDRA",
  SAVINGS_POOL: "KT18zVySfjcmot2HdsDyv8ScokDHFS9PmsAW",
  DEXES: {
    QUIPUSWAP: {
      POOL: "KT1K4EwTpbvYN9agJdjpyJm4ZZdhpUNKB3F6",
      FA1_2_FACTORY: "KT1Lw8hCoaBrHeTeMXbqHPG4sS4K1xn7yKcD",
      FA2_FACTORY: "KT1SwH9P1Tx8a58Mm6qBExQFTcy2rwZyZiXS",
    },
    PLENTY: {
      POOL: "KT1UNBvCJXiwJY6tmHM7CJUVwNPew53XkSfh",
      PLENTY_QUIPUSWAP_POOL: "KT1X1LgNkQShpF9nRLYw3Dgdy4qp38MX617z",
      PLENTY_TOKEN: "KT1GRSvLoikDsXujKgZPsGLX8k8VvR2Tq95b",
    },
  },
  KOLIBRI_BAKER: "tz1abmz7jiCV2GH2u81LRrGgAFFgvQgiDiaf",
  GOVERNOR: "KT1JBmbYxTv3xptk2CadgEdMfjUCUXKEfe5u",
  PAUSE_GUARDIAN: "KT1VWKfxhcwJ8H7aRYEYjwaqAfBSQk4J7zAw",
  BREAK_GLASS_MULTISIG: "KT1PQXekmMqzhT1NHn9QmehEFKQWbkvM6eP2",
  FUND_ADMIN: "KT1Le2tWBZv8KLQKJmZfLTVYiyaTELtx6zQW",
  DAO: "KT1WZ1HJyx5wPt96ZTjtWPotoPUk7pXNPfT2",
  DAO_TOKEN: "KT1JkoE42rrMBP9b2oDhbx6EUr26GcySZMUH",
  DAO_COMMUNITY_FUND: "KT1RyoAZJ3za3FzYsTJYvqzzq4oEW5xnumdQ",
  FARMS: {
    KUSD: {
      farm: "KT1HDXjPtjv7Y7XtJxrNc5rNjnegTi2ZzNfv",
      reserve: "KT1GmtXscYcFhgpcXDuY6Dk6hYqpErsYmxp2",
    },
    QLKUSD: {
      farm: "KT18oxtA5uyhyYXyAVhTa7agJmxHCTjHpiF7",
      reserve: "KT1XqMecdis3bZTeLQn6qVYPsWNoh9cWtbot",
    },
    KUSD_LP: {
      farm: "KT1RB179ddATKbCi7E8ben91bo2hqRRPrNQf",
      reserve: "KT1UUZvqqBpR6oku4YDxb1oDDfxrfiKaAMgA",
    },
    YOUVES_FLAT: {
      farm: "KT1VTA694ZHFQPtxg76HzY7gHdvi7idYEYje",
      reserve: "KT1FX66x7T94o6PVuY2cLc6mNUUHEzRs8yqM",
    },
  },
  PAYMENT_VAULTS: {
    tz1YeYpdJshsXxkPdSdKUJaF1QmH1ngCrJ7V: ["KT1JyC6ShDjT9DtdjZAjWFsvuQuev2f49UXn"],
    tz1cNABC2qtbbHKDDKdvxRkcyopL1kEfbpgV: ["KT1A4N9amP26gjPknxAsVZNP5xgLGu4yqKka"],
    tz1Xh11mHYWxbYHv55AVhsPPPJeSp8PunERB: ["KT1TDgMJA7daH2Dg271dXV3SAMLfhd4kiJGb"],
    tz1LN3hTUtg8eohArm2T1S4wwxbbrY4umr3a: ["KT18p9uowCTqYZ5vnP2w3DQaErFSUZ6ancLS"],
    tz1fxDQFyL3QEhV2jgSd3YqKx2FKj5yA63RK: ["KT1DhZVp3oZgqH3rACrjckSD6znTx4B6UHTN"],
    tz1bthMuA6Yzgqnp5dtQanF6C98USvgTJYSg: ["KT1DtzEqqaALZc3r6GSQQU9DEEw77FNRfxop"],
  },
  VOTING_VAULTS: {
    tz1YeYpdJshsXxkPdSdKUJaF1QmH1ngCrJ7V: "KT1JyC6ShDjT9DtdjZAjWFsvuQuev2f49UXn",
    tz1cNABC2qtbbHKDDKdvxRkcyopL1kEfbpgV: "KT1A4N9amP26gjPknxAsVZNP5xgLGu4yqKka",
    tz1Xh11mHYWxbYHv55AVhsPPPJeSp8PunERB: "KT1TDgMJA7daH2Dg271dXV3SAMLfhd4kiJGb",
  },
  BREAK_GLASS_CONTRACTS: {
    MINTER: "KT1TrqGSqnnkbaRUjTNFfd2BWnpAk6MocnwX",
    OVEN_PROXY: "KT1FTT7CYwEqJErbGkk6ZrWonLtYa8SpTEbH",
    OVEN_FACTORY: "KT1WaraYWQajJtTW3hrotyRvyFUJ5WowXhD5",
    TOKEN: "KT1DEEcqJkjWPeTho3RSRfeEkz7aCSgnJXrM",
    OVEN_REGISTRY: "KT1GCYq8c1xZghVACX52PgX37wJbWXnaokFG",
    DEVELOPER_FUND: "KT1F3QqU1dYEiyQAyk5dRb2TbXF2H3KDZyQa",
    STABILITY_FUND: "KT1AtiyBDsqxotB6z5RPd782q6hkoQ8WK8Nt",
    ORACLE: "KT1WWBdDDGTnrBaRih2BvsevvqiC9p4gT1D5",
    LIQUIDITY_POOL: "KT1FC288PPN87gtmTKRuHVUhoJ1Z8T4KBUAD",
    SAVINGS_POOL: "KT1Nmg6hDcBHRxgNDCPmaecQjLtNtKPKchB1",
    DAO_COMMUNITY_FUND: "KT1LdS5mBkTzrjacqgJ1FMZNmaSoUazZXSuR",
    PAYMENT_VAULTS: {
      tz1YeYpdJshsXxkPdSdKUJaF1QmH1ngCrJ7V: ["KT1M7YNrcUawwFStCoi9SvMm45siDFS5CnU7"],
      tz1cNABC2qtbbHKDDKdvxRkcyopL1kEfbpgV: ["KT1DURQAFr1D7Szc9SHyZ4R3ZFL4tpqegzTW"],
      tz1Xh11mHYWxbYHv55AVhsPPPJeSp8PunERB: ["KT1B9RF7Ym5ovLtH3tbpVKKeUcnYKa9dZ4zi"],
    },
  },
};

const HANGZHOUNET: ContractGroup = {
  MINTER: "KT1ECitbrVyYeVQJQXC8CLpyGsumSXNjm72R",
  OVEN_PROXY: "KT1Qd8gG2uqPrpTiykxPY8omJzR3Rf9A53fg",
  OVEN_FACTORY: "KT1GpuNB3CBnX7vv9fdfNbisUqJpXgb1SQxr",
  TOKEN: "KT1MDQ2wiBTKnkznULsdKgpyf9AL9qsF3x7C",
  OVEN_REGISTRY: "KT1U4dr4RHRWBTUQ9Fj63k78RYNB4diqvMUy",
  DEVELOPER_FUND: "KT1LJEQMzwHRTceGmGPR8tbAH5mMSkPXFZPv",
  STABILITY_FUND: "KT1JPwovHNegWZLpxGNrNd64m9LiYkhCiEhQ",
  ORACLE: "KT1FBFtoqsodkLRQndRsrcrCv5VMdFik6ZU4",
  HARBINGER_NORMALIZER: "KT1PMQZxQTrFPJn3pEaj9rvGfJA9Hvx7Z1CL",
  YOUVES_PROXY: null,
  LIQUIDITY_POOL: "KT1Wt4bHiSaZjA35FdyXV1bBhLFTEo9DudKB",
  SAVINGS_POOL: null,
  DEXES: {
    QUIPUSWAP: {
      POOL: "KT1HbTh2sCEJjRds46DxBUUYqtKpZDWPMJNJ",
      FA1_2_FACTORY: "KT1HrQWkSFe7ugihjoMWwQ7p8ja9e18LdUFn",
      FA2_FACTORY: null,
    },
    PLENTY: { POOL: null, PLENTY_QUIPUSWAP_POOL: null, PLENTY_TOKEN: null },
  },
  KOLIBRI_BAKER: "tz1aWXP237BLwNHJcCD4b3DutCevhqq2T1Z9",
  GOVERNOR: "KT1QRWpDtE6ZK4gBpZKpjfrN2QJN5MjQZuxD",
  PAUSE_GUARDIAN: "KT1QvrDcaket7jsLF6jyUma9ixFkH4jH1J99",
  BREAK_GLASS_MULTISIG: "KT1LHF8Uc5MWgnHHHSvkbkcrd8FiRVh4L1tF",
  FUND_ADMIN: "KT1QvrDcaket7jsLF6jyUma9ixFkH4jH1J99",
  DAO: "KT1LTnsLdnc4QcdtQPXWrqy5nx2QfJ1cHXpy",
  DAO_TOKEN: "KT1JxNEcPUTVwqKzaBe2cAw6rQmjF5Kx7CmG",
  DAO_COMMUNITY_FUND: "KT1MfDcTYvqjNmjQKHRxr9YDphLTtMUYHbvG",
  FARMS: {
    KUSD: {
      farm: "KT1AUFT5ySxK2UE63x689X3V26wt48UkiMWK",
      reserve: "KT1Rpns7j1o53SRSAcLoaEMW8t7YbfgqNsxC",
    },
    QLKUSD: {
      farm: "KT1RLPgXPofFdfKNc7ckbjm4bAwk1RMDqhDB",
      reserve: "KT1XdY1J9ZJXTHngX8EewVDUzqSa1mUGTfXF",
    },
    KUSD_LP: {
      farm: "KT1TscJ89RMksEb4CEca41hJo49Fyhicmqgv",
      reserve: "KT1UpoukRNFNYykzuSxjVqfUXa5ApzUcPqZB",
    },
    YOUVES_FLAT: { farm: null, reserve: null },
  },
  PAYMENT_VAULTS: {
    tz1YeYpdJshsXxkPdSdKUJaF1QmH1ngCrJ7V: ["KT1UpziYhnqkLmhHhjBKAf4Z4VqPDW9jaK7J"],
    tz1Xh11mHYWxbYHv55AVhsPPPJeSp8PunERB: ["KT1NVBwsunSuFwxUWki5Y5ZW7voaXahGUpWf"],
    tz1cNABC2qtbbHKDDKdvxRkcyopL1kEfbpgV: ["KT1D1UyDWN2Q52SENuWjq8DdxVqqsmqQT1JQ"],
  },
  VOTING_VAULTS: {
    tz1YeYpdJshsXxkPdSdKUJaF1QmH1ngCrJ7V: "KT1UpziYhnqkLmhHhjBKAf4Z4VqPDW9jaK7J",
    tz1Xh11mHYWxbYHv55AVhsPPPJeSp8PunERB: "KT1NVBwsunSuFwxUWki5Y5ZW7voaXahGUpWf",
    tz1cNABC2qtbbHKDDKdvxRkcyopL1kEfbpgV: "KT1D1UyDWN2Q52SENuWjq8DdxVqqsmqQT1JQ",
  },
  BREAK_GLASS_CONTRACTS: {
    MINTER: "KT1PuF7NbRKZTyxHsijboUobFrSQFFCG2uDf",
    OVEN_PROXY: "KT1HeWCmuEGsyE3czZ33hz1ViZYQF9xu8jLH",
    OVEN_FACTORY: "KT1QAiqr7TfMvQu1g7DCBoHnR6mEsRD6UstC",
    TOKEN: "KT1QK94ic1fdkRqTuz65MGBVZgsUshaAGajh",
    OVEN_REGISTRY: "KT1KCbEcRNXe2xHQQxZp2vd8Z2gAKAHnyoun",
    DEVELOPER_FUND: "KT1DNwiDbWSWC7Ds2dtJDsapsGjHQ2PG8Nwn",
    STABILITY_FUND: "KT1M5mg5SnwmAVxRpSByJuZA6jVxwAbkimoF",
    ORACLE: "KT1KgFbmCzM7zAUUTcEaRY8ihLqP4qbECnhU",
    LIQUIDITY_POOL: "KT1GgmsuYQKGZijaftRELjHuTUF7bFvHurY3",
    SAVINGS_POOL: null,
    DAO_COMMUNITY_FUND: "KT197Z7Ajs3xDzACJgJH2GS4c3HkwKyiKC7A",
    PAYMENT_VAULTS: {
      tz1YeYpdJshsXxkPdSdKUJaF1QmH1ngCrJ7V: ["KT1MzxAPTk1rcrf3QtfPFQdAG3TCCpwzBqGB"],
      tz1Xh11mHYWxbYHv55AVhsPPPJeSp8PunERB: ["KT1X4ZjbEWSPZsMbBy9FT5LfhWfUQHG6dvD9"],
      tz1cNABC2qtbbHKDDKdvxRkcyopL1kEfbpgV: ["KT1Kb5Pd9KtZ3RzoQnu1jrkskbGJG94fRhcb"],
    },
  },
};

const SANDBOXNET: ContractGroup = {
  MINTER: "KT1C5AC8HootcoyUXxayUQoVMHaAeXB2YqDC",
  OVEN_PROXY: "KT1VcBAevCCeZJe5C2WGyjrHGt8PZnEEy7AA",
  OVEN_FACTORY: "KT1Xp9CgidYGbZdopfTW1JQsrD8i5wzHYT8b",
  TOKEN: "KT1MDof21NLULskssbUv7rZuNYpCboB6tyQu",
  OVEN_REGISTRY: "KT1BRocb23Ec3V7Lk1tXep2fmhuBAZU7PeZm",
  DEVELOPER_FUND: "KT1AD7BikbRdvpAyWUTFT5mN3jgADL7Huv7B",
  STABILITY_FUND: "KT1EcNmD12afdpSSKi98fKh8sS3zEecWrZ5w",
  ORACLE: "KT1HBPxqRKLWFs3ttM3fq3vyhp4bods6iam7",
  HARBINGER_NORMALIZER: "KT1JFhDzhu6UDFFpNVLUoBtVQG5DGztSuiEn",
  YOUVES_PROXY: null,
  LIQUIDITY_POOL: "KT1SRz4kQsXTc38UVJjWJMLBr82Dh5j8RF9i",
  SAVINGS_POOL: "KT1CVJDSJ9Lr6zQxVtcgwuCJjZ5SQCcWDFrv",
  DEXES: {
    QUIPUSWAP: {
      POOL: "KT1RaeQ8f9PmK5hXm4x67mbvWYvKgUEv1Yd4",
      FA1_2_FACTORY: "KT1D69FXbocGJsHTbVThcgZ1kUkESYUk3Ruj",
      FA2_FACTORY: null,
    },
    PLENTY: { POOL: null, PLENTY_QUIPUSWAP_POOL: null, PLENTY_TOKEN: null },
  },
  KOLIBRI_BAKER: null,
  GOVERNOR: "KT1LEghbyN9QK8VrQjtdqbutz6jT9Z5pTFBb",
  PAUSE_GUARDIAN: "KT1Pmnp8NvEMCojim1iidAfKqEv4Hw1ZSrE3",
  BREAK_GLASS_MULTISIG: "KT1MFLf5SFgKszdjxXqJhgrgcXASzBLNYoUY",
  FUND_ADMIN: null,
  DAO: "KT1PSp5X6hEwpxwUCLNL2QaEgssqSfWuQV2K",
  DAO_TOKEN: "KT1MMHnHYpzRZQxwZBKPizRMtnM7fNQQbfxC",
  DAO_COMMUNITY_FUND: "KT1EHLq2THz7X7hxMHJfqyfm2D65oTEten2j",
  FARMS: {
    KUSD: {
      farm: "KT1XE7JisZ6AAiBC1KZrWbfKikndLDtrd5Q3",
      reserve: "KT1VR3213e2jPYsadgggqdtCSwymu4CZeWng",
    },
    QLKUSD: {
      farm: "KT1N2JDDNLdHrMdza9mfZX8axzFgX4bNY9VW",
      reserve: "KT1ATzmQq5nre99NZh8f1mSiJV6xFkRvamgJ",
    },
    KUSD_LP: {
      farm: "KT1FEDmCoGLBCo5mt6sLUQDc97bNUSAbuLtN",
      reserve: "KT1FC1sokSrECjxNkdt8AVBvPtTDpWyiaECb",
    },
    YOUVES_FLAT: { farm: null, reserve: null },
  },
  PAYMENT_VAULTS: {
    tz1VSUr8wwNhLAzempoch5d6hLRiTh8Cjcjb: ["KT1XUKeMZDTeAQNEYrhif61BkcSjbERR6Kav"],
  },
  VOTING_VAULTS: {
    tz1VSUr8wwNhLAzempoch5d6hLRiTh8Cjcjb: "KT1XUKeMZDTeAQNEYrhif61BkcSjbERR6Kav",
  },
  BREAK_GLASS_CONTRACTS: {
    MINTER: "KT1Q5N3KZtsyo7TTLFfWSmk98bBaFdFe44hm",
    OVEN_PROXY: "KT1T4qDyNsGEnxprtChrL59Hmaw6iLUDEtuz",
    OVEN_FACTORY: "KT1JaMew4SysUS28yaBpsgyKfYe2Vbuce592",
    TOKEN: "KT1RvthAPoUWEiFSxbPnBwU1Zm8K6CprFeTV",
    OVEN_REGISTRY: "KT1VJba14CRj2kkKLvsyXgXtsmVuGMhgbeNf",
    DEVELOPER_FUND: "KT1B4bx8vVw3mb5aaTXN7qDzTQDu6UUC9ciQ",
    STABILITY_FUND: "KT18nKvHJYDtqua7ATHStAofiYM5Wx9HPxuq",
    ORACLE: "KT1PGrMN85JYw9d6eCHgJeZ6ceViDCtFhQ6F",
    LIQUIDITY_POOL: "KT1Xpj5rigkMK3TNexHiehkVnscWKRyyyJBb",
    SAVINGS_POOL: "KT1WnKoVnBWPA8VUqMYfVfMgiX6pda5Z8gNn",
    DAO_COMMUNITY_FUND: "KT1SVzcqJE9Hvo5PjtxRTTYSThpQEaaFNGHy",
    PAYMENT_VAULTS: {
      tz1VSUr8wwNhLAzempoch5d6hLRiTh8Cjcjb: ["KT1N8xjKYSawu93uG8LuTHPsYPMeGdWQHffL"],
    },
  },
};

const CONTRACTS: Contracts = {
  ZERO: HANGZHOUNET,
  TEST: HANGZHOUNET,
  MAIN: MAINNET,
  SANDBOX: SANDBOXNET,
};

export default CONTRACTS;
